### DISCUSSION TITLE
Use json schema composition/ allOf mechanism for all profiling needs?

### DISCUSSION THREAD

**Discussion by mbrush** [ga4gh/va-spec#283] [Ideas]
Something to think about - if not for 1.0, for a release shortly after:

At present, we use two distinct mechanisms for defining specializations of core model classes (i.e. authoring what I think of as VA profiles):
 1. an **MSP-based approach** that uses special functions like `inherits` and `extends` - form which MSP code derives profiles as subclasses of core classes (used for Proposition and Study Result profiles)
 2. a **JSON schema composition approach** that uses the `allOf` keyword to extend core class definitions with additional constraints (used for Statement and Evidence Line profiles)

It would be nice if we could use a single mechanism to author all types of profiles - and even better if this mechanism avoids the need for MSP tooling to do so. With this in mind, I feel like the json schema composition paradigm could handle the main profiling operations/needs we have for the v1 release:
 1. It lets us define a named subschema that extend a core VA class, to define a 'profile' that can be referenced from other objects in VA data. 
 2. It lets us 'overwrite' characteristics of existing core class attributes in a profile definition, with refined descriptions and constraints (e.g. data type/enum bindings, cardinality, etc.)
 3. It can be used to 'rename' the overwritten core attributes in a profile definition (e.g. object -> objectCondition) - this requires a delete and replace approach (see below)  . . . but IMO we should not be renaming attributes in profiles anyway.
 4. It lets us add new attributes not included in the core class (e.g. qualifiers in Statements)
  
Below I provide examples of using the json schema composition mechanism to author va profiles for each core class type (Proposition, StudyResult, EvidenceLine, Statement).

If these do what we want, might we consider using the json schema profiling mechanism to author all VA Profiles . . . at least in the short term until we devlep better tooling support for profile authoring?

It would be very little work to refactor our existing yaml profile definitions to use this on mechanism. However, it would require updates to MSP code if we wanted to generate RTD documentation from profile specifications.  So perhaps if we like this idea, we might move toward it after PSC review?

Finally, keep in mind that I have been working with the LinkML team a bit to explore how the LinkML framework can support VA-Spec generally, and profile authoring needs in particular. I hope to have a demo to present about this in the next month or two.  They are excited about our use case, and keen to dedicate developer time to help. I am optimistic that this will provide a solution we should seriously consider migrating to in the near future.  

-----------------

### 1. A Proposition Profile (Variant Pathogenicity Proposition): 
Defined using the json schema composition/ allOf mechanism below.  (Compare to the current way of authoring this profile using MSP keywords [here ](https://github.com/ga4gh/va-spec/blob/1.0.0-ballot.2025-03/schema/va-spec/base/va-core-source.yaml#L862) . . . both approaches take the same number of lines)
 
``````

  VariantPathogenicityProposition:
    maturity: trial use
    description: >-
      A proposition describing the role of a variant in causing a heritable condition.
    allOf:
    - $ref: "/ga4gh/schema/gks-core/1.x/json/ClinicalVariantProposition"
    - properties:
        type:                              # Example of 'overwriting' a core attribute with specific constraints and description.
          const: VariantPathogenicityProposition
          description: Must be "VariantPathogenicityProposition"
        predicate:
           default: isCausalFor
        object: false                      # Example of attribute 'renaming' an attribute through a 'remove and replace' approach. Here it declares the core 'object' attribute to be 'false' and thus cannot be used - and then replaces it with the `objectCondition` attribute below.  Note that 'object' could not be a required property in parent Proposition core class, as this would introduce an inconsistency, but I think that is fine. 
        objectCondition:                   # Replaces the "removed"  'object' attribute with 'objectCondition'
          description: The :ref:`Condition` for which the variant impact is stated.  Replaces the va-core 'object' attribute in this Proposition profile.
          oneOf:
            - $ref: Condition
            - $refCurie: gks.core:iriReference
        penetranceQualifier:               # Example of adding a 'new' attribute - which is allowed with json schema profiling
          $refCurie: gks.core:MappableConcept
          description: >-
            Reports the penetrance of the pathogenic effect - i.e. the extent to which the
            variant impact is expressed by individuals carrying it as a measure of the
            proportion of carriers exhibiting the condition. 
        modeOfInheritanceQualifier:
          $refCurie: gks.core:MappableConcept
          description: >-
            Reports a pattern of inheritance expected for the pathogenic effect of the variant.
            HPO terms within the hierarchy of 'HP:0000005' (mode of inheritance) are recommended
            to specify.
      required:
        - predicate
        - objectCondition
        
``````

 -----

### 2. A Study Result Profile (Cohort Allele Frequency)
Defined using the json schema composition/ allOf mechanism. (Compare to the current way of authoring this profile using MSP keywords [here ](https://github.com/ga4gh/va-spec/blob/1.x/schema/va-spec/base/va-core-source.yaml#L964).

````

$defs:
  CohortAlleleFrequencyStudyResult:
    maturity: trial use
    description: >-
      A StudyResult that reports measures related to the frequency of an Allele in a cohort
    allOf:
    - $ref: "/ga4gh/schema/gks-core/1.x/json/StudyResult"
    - properties:
        type:
          const: "CohortAlleleFrequencyStudyResult"
          description: MUST be "CohortAlleleFrequencyStudyResult".
        sourceDataSet:          # overwrites core 'sourceDtaSet property' with updated description.
          description: The dataset from which the CohortAlleleFrequencyStudyResult was reported.
        focus: false               # replace 'focus' with 'focusAllele' 
        focusAllele:                    
          description: The Allele for which frequency results are reported.  Replaces the va-core 'focus' attribute in this StudyResult profile.
          oneOf:
          - $refCurie: vrs:Allele
          - $refCurie: gks.core:iriReference
      focusAlleleCount:           # this and the attributes that follow are just new properties, which we are allowed to add in json schema profiling
        type: integer
        description: The number of occurrences of the focusAllele in the cohort.
      locusAlleleCount:
        type: integer
        description: >-
          The number of occurrences of all alleles at the locus in the cohort.
      focusAlleleFrequency:
        type: number
        description: The frequency of the focusAllele in the cohort.
      cohort:
        $ref: StudyGroup
        description: The cohort from which the frequency was derived.
      subCohortFrequency:
        type: array
        ordered: false
        description: >-
          A list of CohortAlleleFrequency objects describing subcohorts of the cohort currently being described.
          Subcohorts can be further subdivided into more subcohorts. This enables, for example, the description 
          of different ancestry groups and sexes among those ancestry groups.
        items:
          $ref: "#/$defs/CohortAlleleFrequencyStudyResult"
    required:
    - focusAllele
    - focusAlleleCount
    - locusAlleleCount
    - focusAlleleFrequency
    - cohort
    
 ````   

------

### 3. An Evidence Line Profile (Pathogenicity Evidence Line, Oncogenicity Evidence Line)
These are already defined using the json schema composition/ allOf mechanism - no reliance on MSP. See [here](https://github.com/ga4gh/va-spec/blob/1.0.0-ballot.2025-03/schema/va-spec/acmg-2015/pathogenicity-evidence-line-profile-source.yaml). 

However, I would propose declaration of a more specific `type` for Statements, following the pattern used in the Proposition and StudyResult profile examples above.
     
-------

### 4. A Statement Profile (Variant Pathogenicity)
These are already defined using the json schema composition/ allOf mechanism - no reliance on MSP. See [here](https://github.com/ga4gh/va-spec/blob/1.0.0-ballot.2025-03/schema/va-spec/acmg-2015/pathogenicity-statement-profile-source.yaml). 

However, I would propose declaration of a more specific `type` for Statements, following the pattern used in the Proposition and StudyResult profile examples above.

-------

Finally, I think there could still be a role for MSP-like tooling to transform the allOf-based yaml profile into a more explicit json schema and web docs where all attributes of the profile are explicitly declared (instead of as a diff from the core class being profiled).
