### ISSUE TITLE
Requirements for `focusAllele` within `subCohortFrequency`

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#245]
_Originally posted by @Mrinal-Thomas-Epic in https://github.com/ga4gh/va-spec/discussions/234#discussioncomment-11465693_:

Can `focusAllele` within members of `subCohortFrequency` be different from the `focusAllele` in the parent `CohortAlleleFrequencyStudyResult`? If so, what does that mean and how different can they be? If not, why allow specifying the allele twice (rather than using a different class for subCohortFrequency members)?
<details>
<summary>Example:</summary>

```yaml
id: parentStudyResult
focusAllele:
  location:
    sequenceReference:
      id: NC_000001.11
      ...
    start: 1000
    end: 1001
  state:
    type: LiteralSequenceExpression
    sequence: C
specifiedBy: <...>
...

subCohortFrequency:
- id: childStudyResult1
  focusAllele:
    location:
      sequenceReference:
        id: NC_000001.11
        ...
      start: 1005
      end: 1006
    state:
      type: LiteralSequenceExpression
      sequence: T
  ...

- id: childStudyResult2
  ...
```

</details>
