### ISSUE TITLE
Domain Entity Required Fields (& Absent Concepts)

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#253]
_Originally posted by @korikuzma in https://github.com/ga4gh/va-spec/discussions/234#discussioncomment-11620397_:

Is there a reason why there are no required fields in the domain entity schemas? https://github.com/ga4gh/va-spec/blob/1.0.0-ballot.2024-11.2/schema/va-spec/base/domain-entities-source.yaml 

I would assume that we would want `TraitSet.traits` and `TherapyGroup.therapies` to be required

**Comment by mbrush** [comment]
For TraitSets, I think the rationale is that this supports cases where no Condition is specified by the data provider.  e.g. it is not uncommon for Pathogenicity Statements from ClinVar to have a TraitSet with no members - indicating that no `objectCondition` was specified.  

However, it was noted that: (1) this would be inconsistent with the `minItems:2` constraint on this class; and (2) there is general agreement that a means to explicitly state that no Condition was specified is preferred over one that omits the value and leaves consumers guessing as to why.

It was proposed that we explore using the `conceptType` or `primaryCode` attributes of a `MappableConcept` to capture a term such as "not specified" that explicitly reports that a Condition was not specified in this case. This pattern would be more generally useful anytime a value is not specified in the source data, and we want to explicitly report this in the data. 

This idea will be considered in discussions around other issues related to MappableConcept/ConceptMapping/Coding (https://github.com/ga4gh/va-spec/issues/251, https://github.com/ga4gh/va-spec/issues/254, https://github.com/ga4gh/va-spec/issues/259)

----

In either approach (`conceptType` or `primaryCode`), the implementation would likely involve informally defining a convention in the attribute description about how to populate these fields in cases where a data provider does not report a condition/trait.
(e.g. with a value like "Not Specified").  Consider what the data might look like in either approach:

**Using `primaryCode` (this is my preference - clear and not duplicative):**

````
objectCondition:           
  conceptType: Disease
  primaryCode:  Not Specified

````

**Using `conceptType`** (keep in mind that a `label` or `primaryCode` is required . . . all options seem duplicative and less clear IMO):

````
# Option 1:
objectCondition:           
  conceptType: Not Specified 
  name: Not Specified 

# Option 2:
objectCondition:           
  conceptType: Unspecified Disease
  name: Unspecified Disease

# Option 3:
. . . ?

````

**Comment by mbrush** [comment]
**Outcomes of 1-29-25 Discussion:** 
- The real issue here concerns how to indicate when no condition is provided.  The reason why `traits` were not initially required in the `TraitSet` model is to allow for this to be null when no condition is provided. 
- However, as noted, this violates the stated cardinality constraints on this attribute. 
- And we decided it was better to explicitly indicate that no condition is specified (rather than rely on an empty field in the data)
- Here we decided to use the `conceptType` attribute, and recommend the value "Absent" in cases where the source data does not indicate a specific concept. 
- Data providers will also have to provide a value of their choice for EITHER the `name` OR `primaryCoding` attribute as well (as one of these is required). 
- For a name, they may choose a single term to cover all cases (e.g. 'Condition Not Specified'), or choose to provide more precise terms that may indicate why/how it is absent if they wish (e.g. 'data not provided', unknown condition', 'all mendelian diseases')
- Roughly, the  schema may look like the following - providing recommendations informally in the `Condition` description:
````
  Condition:
    maturity: trial use
    description: >-
      A single trait (Disease, Phenotype, etc.) or a set of traits (TraitSet). In cases where no condition is 
      specified by the data provider, use a MappableConcept with conceptType = "Absent".  Additionally,
      as you must and populate either the 'name' or 'primaryCoding' attribute - chose a name or code to
      communicate the specific nature or reason for the lack of a condition, as possible (e.g.  'Data Not 
      Provided', 'Unknown Condition', 'All Mendelian Diseases')
    oneOf:
      - $refCurie: gks.core:MappableConcept
      - $ref: "#/$defs/TraitSet"
````

And data may look like the following:
````
 objectCondition:
    conceptType: Absent                                                                     
    name: Unknown Condition
````
   
or
            
````
 objectCondition:
    conceptType: Absent                                                                     
    name: All Mendelian Diseases
````   
or
            
````
 objectCondition:
    conceptType: Absent                                                                     
    name: Data Not Provided
````

Note that with this convention for specifying when a condition is not provided, we can and will require that `TraitSet.traits` is populated.

**Comment by mbrush** [comment]
````
  TraitSet:
    type: object
    maturity: trial use
    inherits: gks-core:Element
    description: >-
      A group of conditions that are manifest in patients.
    properties:
      therapies:
        type: array
        ordered: false
        items:
          $refCurie: gks.core:MappableConcept
        description: >-
          A set of conditions (diseases, phenotypes, traits).
        minItems: 2
      membershipOperator:
        description: The logical relationship between members of the group, that indicates how they manifest 
          in patients.  'AND' indicates that all conditions in the set co-occur together in patients. 'OR' indicates 
         that each condition in the set is manifest alone in a distinct subset of patients in a cohort that was 
         interrogated in a given study.
        type: string
        enum:
           - AND
           - OR
    required:
      - traits
      - membershipOperator
````
