### ISSUE TITLE
Fix `specifiedBy` data type in the Path Funcitonal Evidence Line profile

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#265]
In the definition for the `PathogenicityFunctionalImpactEvidenceLine` profile, the constraint on the `specifiedBy` attribute [here](https://github.com/ga4gh/va-spec/blob/1.x/schema/va-spec/acmg-2015/pathogenicity-functional-impact-evidence-line-profile-source.yaml#L43) binds an enumeration to a `primaryCode` attribute in a nested MappableCopncept object (implied by the fact that `primaryCode` is an attribute of a MappableConcept).

````
        specifiedBy:
          description: >-
            The ACMG criterion that was applied to interpret variant functional impact information 
            as evidence for or against the assessed variant's pathogenicity. 
          properties:
            primaryCode:
              description: >-
                The ACMG 2015 criterion code that was applied to interpret variant functional impact information 
                as evidence for or against the assessed variant's pathogenicity.  Must be one of the following values: BS3 or PS3.
                Conditional requirement:
                * If directionOfEvidenceProvided is 'supports' then the value must be 'PS3'.
                * If directionOfEvidenceProvided is 'disputes' then the value must be 'BS3'.
              type: string
              enum:
                - PS3
                - BS3
````

However, the va-core spec specifies that the `specifiedBy` attribute takes a `Method` (or an `iriReference`) - which does not have a `primaryCode` property. 

````
      specifiedBy:
        oneOf:
        - $ref: "#/$defs/Method"
        - $refCurie: gks.core:iriReference
        description: >-
          A specification that describes all or part of the process that led to creation of the
          Information Entity

````

I think the fix here is to update the profile constraint to bind an attribute of `Method` to the enumerated values desired here.  But not clear which attribute that might be (see [here](https://va-ga4gh.readthedocs.io/en/1.0.0-ballot.2024-11/core-information-model/entities/information-entities/method.html), perhaps `id`, or `label/name`?). Alt, we allow `specifiedBy` to take a `MappableConcept` (but I don't think this is appropriate).

**Comment by mbrush** [comment]
**Outcomes of Discussion on 2-11-25:**

- agreed that the value of the `specifiedBy` attribute needs to be a Method
- decided to not try and capture the specific criterion - just the ACMG guidelines as the method, by way of specifying the ACMG Guideline publication as the document in which the method is reported. 
- roughly (@larrybabb will hone.finalize in his PR):

````
        specifiedBy:
          description: >-
            The guidelines that were followed to interpret variant functional impact information 
            as evidence for or against the assessed variant's pathogenicity. 
          properties:
            reportedIn:
               properties:
                  pmid: 
                    const: "12345"
                  name: 
                    const: "ACMG 2015 Variant Interpretation Guidelines"
````
