### ISSUE TITLE
CIViC AID statements have a `classification` but no `strength`

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#293]
In CIViC AID data examples like [this one,](https://github.com/ga4gh/va-spec/blob/update-civic-test-fixtures/tests/fixtures/civic_aid6.yaml) classifications are represented as below:
 
````
classification:                 
  primaryCode: Tier I
  extensions:
    - name: civic_code
      value: TIER_I_LEVEL_A
````
 
Recall that a Statement `classification` must reiterate what is reported in SPO and `strength` and/or `direction` attributes in the data - i.e. it cannot add info beyond what is captured in these base attributes (see [here](https://github.com/ga4gh/va-spec/blob/update-civic-test-fixtures/schema/va-spec/base/va-core-source.yaml#L475)). 
 
In the CIViC data, AID records, the `classification` indicates a strength for the Statement, but the Statement objects have no `strength` attribute - which breaks this rule.  Recall that we were very careful to stick to this rule in modeling and creating data for Variant Pathogenicity Statements.
