### ISSUE TITLE
Add test case for inline therapeutic response classification

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/va-spec#308]
https://github.com/ga4gh/va-spec/blob/1.0.0-ballot.2025-03/tests/test_definitions.yaml#L76-L78

**Comment by korikuzma** [comment]
It'd be nice to also have the other AMP/ASCO/CAP definitions tested:

```yaml
- test_file: tr-classification-inline.yaml
  namespace: va-spec.aac-2017
  definition: VariantTherapeuticResponseStudyStatement
- test_file: diagnostic-classification-inline.yaml
  namespace: va-spec.aac-2017
  definition: VariantDiagnosticStudyStatement
- test_file: prognostic-classification-inline.yaml
  namespace: va-spec.aac-2017
  definition: VariantPrognosticStudyStatement
```
