### ISSUE TITLE
Update test fixtures GA4GH identifiers to align with VRS 2.0

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/va-spec#359]
I'm working on #357  and noticed the GA4GH identifiers in our tests fixtures are pretty outdated.

For example, https://github.com/ga4gh/va-spec/blob/1.0/tests/fixtures/allele.yaml still uses `VSL` as the VRS type prefix, but in VRS 2.0 it is now `SL`. The computed digests are also wrong. The correct fixture is:

```yaml
id: ga4gh:VA.UwGf_LcI8bGGb-R85AHcMoemp6aOBiKj
location:
  id: ga4gh:SL.AjCGNWtNduOZpVESIIumzjm2EWmfMhIL
  end: 11124516
  start: 11124515
  sequenceReference:
    type: SequenceReference
    refgetAccession: SQ.Ya6Rs7DHhDeg7YaOSg1EoNi3U_nQ9SvO
  type: SequenceLocation
state:
  sequence: T
  type: LiteralSequenceExpression
type: Allele
```

I imagine there are other type prefixes / digests that need to be updated in our test fixtures.
