### ISSUE TITLE
Defining Element extensions 

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#55]
Element extensions are support adding bespoke attributes within existing/core classes.  e.g. key-value based objects where implementers can define new/custom attributes (keys) as a proper part of the model. See the [FHIR ‘extension’ element ](https://www.hl7.org/fhir/extensibility.html)
 
A key requirement is to clearly partition attribute extensions, from the core attributes defined as part of the spec. 
 
One possible solution that has been raised is the **"x-attribute"** approach - where custom attribute names are prefixed with an "x-" and a namespace for the creator (e.g. "ClinGen"), and included as siblings of core attribute. Receivers/users will know that content in x-prefixed attributes is bespoke - and can choose to ignore it. This approach is used by several schema, e.g. that for the [Swagger OpenAPI](https://swagger.io/docs/specification/openapi-extensions/).
 
Another approach is exemplified by the FHIR **'Extension'** element [here](http://hl7.org/fhir/extensibility.html). It provides a flexible 'key-value' data element allowing implementers to define new/custom attributes as a proper part of the model. Receivers/users will know that content in this part of the model is bespoke - and can choose to ignore it.
  
### Examples:
Below we show how each proposal would handle a use case provided by ClinVar- which captures an `OrganizationCategory` for each submitting organization. e.g. Counsyl has the category 'laboratory' in the submission record for SCV000677724. This information is not directly supported by the minimal VA 'Organization' class as proposed in #53.  
 
 
#### x-attribute:
 
````
 
-   id: clinvar:SCV000677724
    type: Variant Pathogenicity Statement
    authoredBy: 
      - id: clinvar:320494
        type: Organization
        label: Counsyl
        description: the Counsyl Genetic Screening laboratories at Myriad Health
        url: https://www.ncbi.nlm.nih.gov/gtr/labs/320494/ 
        x-clingen-organizationCategory: laboratory
 
````
 
#### Extension Element
 
````
 
-   id: clinvar:SCV000677724
    type: Variant Pathogenicity Statement
    authoredBy: 
      - id: clinvar:320494
        type: Organization
        label: Counsyl
        description: the Counsyl Genetic Screening laboratories at Myriad Health
        url: https://www.ncbi.nlm.nih.gov/gtr/labs/320494/ 
        extension: 
           - name: organizationCategory
             value: laboratory
 
````
 
If we choose the extension element approach, the extension attribute would be available for any Class in the model - likely captured in a high-level 'Entity' superclass, along with other universal attributes such as 'id', 'type', 'label', and 'description'.  And 'extension' would be defined as a complex data type that includes two attributes of its own (key, and value).
 
**Extension:**
- name: string | coding | url  (1..1)
- value: string | coding | boolean (1..1)
 
 
Regardless of what approach we select, see the FHIR extension element documentation ([link](https://www.hl7.org/fhir/extensibility.html), [link](https://www.hl7.org/fhir/extensibility-examples.html)) for ideas about governance around creation and use of extension elements by implementations.
